### PR TITLE
Using get_closest_marker instead of get_marker

### PR DESCRIPTION
**Pull request by avshalomt2**
Solves the issue I opened here:
https://github.com/shawnbrown/datatest/issues/42

### CODE REVIEW

**Comment by avshalomt2** [comment]
You might consider writing a test that raises an exception with pytest>=3.6

**Comment by shawnbrown** [comment]
> You might consider writing a test that raises an exception with pytest>=3.6

Absolutely. One thing I plan to do is more-closely integrate the testing of the pytest plugin with datatest as a whole--currently the plugin tests are handled in a separate development-only repository (https://github.com/shawnbrown/pytest-datatest).

**Comment by avshalomt2** [comment]
Wow, you were quick :)
Do you plan to deploy a stable build to pip in the near future?

**Comment by shawnbrown** [comment]
I will look at pushing a patch to fix #42 later today as **0.9.3**.

And in February, I will be releasing **0.9.4** with some additional features:​
* Added builtin validation options for approx, subset, superset, unique,
  fuzzy, etc.
* Added builtin allowance for fuzzy matching.
* Added Predicate class to formalize behavior and provide inverse-matching
  with the inversion operator (~).
* Added unwrap() method to the Query class to unwrap single-item sequences
  or sets.
* Fixed improper use of assert statements with appropriate conditional
  checks and error behavior.
* Added BaseRequirement class to formalize requirement behavior with a
  new class hierarchy. This provides a cleaner way for users to implement
  custom validation behavior and makes the underlying codebase easier to
  maintain.
* Changed "How To" examples using the new validation options.
* Added improved docstrings for Query methods.

**Comment by shawnbrown** [comment]
OK. The patch release has been pushed to PyPI (https://pypi.org/project/datatest/#history).

You should be able to upgrade from PyPI with:

    pip install -U datatest

2019-01-29 (0.9.3)
------------------

* Changed bundled pytest plugin to version 0.1.3:
    * This update adds testing and support for latest versions of Pytest
      and Python (now tested using Pytest 3.3 to 4.1 and Python 2.7 to 3.7).
    * Changed handling for 'mandatory' marker to support older and newer
      Pytest versions.

**Pull request merged**
